### PR TITLE
Set up .eslintrc.json to provide consistent code styling

### LINKED ISSUE #6: Define common code format
It would be great to have a common format specification for the components.

At least have all the vue components with same format:
* I recommend 2 spaces for javascript code and 4 for html part
* set up [.eslintrc.json](https://eslint.org/docs/user-guide/configuring)

### PR DESCRIPTION
**Pull request by cbeard87**
Move eslintConfig into .eslintrc.json to provide rules for consistent code styling. Add .eslintignore to prevent linting of node_modules and .vscode config folders.

Closes #6

### CODE REVIEW

**Comment by petrsvihlik** [comment]
Hi @cbeard87 , thanks for the PR. Since @Simply007 is enjoying summer somewhere far away, I kindly asked @Enngage for a review :)

**Comment by cbeard87** [comment]
Thanks @petrsvihlik! @Enngage I kept the default config pretty minimal, but tried to follow Vue CLI's stylistic conventions as closely as possible.

**Comment by cbeard87** [comment]
@Enngage When I ran the linter locally the majority of the files were affected, especially the Vue components. This indent config option was actually suggested by @Simply007 in the original issue. The intended goal was for Vue template blocks to default to 4 space indents, while preserving 2 space indents in the script blocks and throughout the rest of the codebase.

I'll get the rule for single quotations added in. I didn't add it initially because I wasn't sure what the preferred setting was just by looking through the files.

As for running the linter and pushing up the resulting fixes, I was actually thinking about automating it and running the linter in a git hook. That way, all pushes to the repo will come through with uniform formatting. Thoughts?

**Comment by ChristopherJennings** [comment]
@cbeard87 & @Enngage, let's go ahead with those proposed changes and update the formatting of the files to pass linting as part of this PR.

**Comment by petrsvihlik** [comment]
Hi @cbeard87 , do you have enough information from us to proceed with the changes?

**Comment by cbeard87** [comment]
@petrsvihlik Yes! Apologies, I've been keeping pretty busy at the day job. I'll get those changes made this weekend and revise the PR.

**Comment by petrsvihlik** [comment]
@cbeard87 thanks, awesome! looking forward to it :)

**Comment by cbeard87** [comment]
@petrsvihlik & @Enngage I've revised the PR with the discussed updates. Please note that as linting is now set up to run as part of the precommit process, all of the .vue and .js files were autocorrected during this commit.

**Comment by petrsvihlik** [comment]
lgtm. thank you @cbeard87 !

**Pull request merged**
