### PR TITLE
add article id to article detail route

### PR DESCRIPTION
**Pull request by Simply007**
It would be better to wait for #9.

Currently, it is impossible to go to the eng article and then change the language to Spanish culture (URL slug remain the same).

The solution is similar to one in react sample app:
* https://github.com/Kentico/cloud-sample-app-react/commit/850b811313d1c9bddaa9917dc3133bc0a50fefd7

### CODE REVIEW

**Comment by petrsvihlik** [comment]
@Simply007 could you please resolve the conflicts?

**Comment by Simply007** [comment]
@petrsvihlik conflict is fixed (tested)

**Comment by petrsvihlik** [comment]
the only thing we need to solve in the future are the language-specific URLs...the current handling is not according to a best practice

**Comment by Simply007** [comment]
We will solve it as a part of the issue:

Internal link:
https://kentico.atlassian.net/browse/DC-491

**Pull request merged**
